/**
 * Autogenerated by Thrift Compiler (1.0.0-dev)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef PingPong_H
#define PingPong_H

#include <thrift/TDispatchProcessor.h>
#include <thrift/async/TConcurrentClientSyncInfo.h>
#include "robocup_types.h"



#ifdef _WIN32
  #pragma warning( push )
  #pragma warning (disable : 4250 ) //inheriting methods via dominance 
#endif

class PingPongIf {
 public:
  virtual ~PingPongIf() {}
  virtual void ping(std::string& _return, const std::string& msg) = 0;
  virtual double evaluate(const double msg) = 0;
};

class PingPongIfFactory {
 public:
  typedef PingPongIf Handler;

  virtual ~PingPongIfFactory() {}

  virtual PingPongIf* getHandler(const ::apache::thrift::TConnectionInfo& connInfo) = 0;
  virtual void releaseHandler(PingPongIf* /* handler */) = 0;
};

class PingPongIfSingletonFactory : virtual public PingPongIfFactory {
 public:
  PingPongIfSingletonFactory(const boost::shared_ptr<PingPongIf>& iface) : iface_(iface) {}
  virtual ~PingPongIfSingletonFactory() {}

  virtual PingPongIf* getHandler(const ::apache::thrift::TConnectionInfo&) {
    return iface_.get();
  }
  virtual void releaseHandler(PingPongIf* /* handler */) {}

 protected:
  boost::shared_ptr<PingPongIf> iface_;
};

class PingPongNull : virtual public PingPongIf {
 public:
  virtual ~PingPongNull() {}
  void ping(std::string& /* _return */, const std::string& /* msg */) {
    return;
  }
  double evaluate(const double /* msg */) {
    double _return = (double)0;
    return _return;
  }
};

typedef struct _PingPong_ping_args__isset {
  _PingPong_ping_args__isset() : msg(false) {}
  bool msg :1;
} _PingPong_ping_args__isset;

class PingPong_ping_args {
 public:

  PingPong_ping_args(const PingPong_ping_args&);
  PingPong_ping_args& operator=(const PingPong_ping_args&);
  PingPong_ping_args() : msg() {
  }

  virtual ~PingPong_ping_args() throw();
  std::string msg;

  _PingPong_ping_args__isset __isset;

  void __set_msg(const std::string& val);

  bool operator == (const PingPong_ping_args & rhs) const
  {
    if (!(msg == rhs.msg))
      return false;
    return true;
  }
  bool operator != (const PingPong_ping_args &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const PingPong_ping_args & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class PingPong_ping_pargs {
 public:


  virtual ~PingPong_ping_pargs() throw();
  const std::string* msg;

  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _PingPong_ping_result__isset {
  _PingPong_ping_result__isset() : success(false) {}
  bool success :1;
} _PingPong_ping_result__isset;

class PingPong_ping_result {
 public:

  PingPong_ping_result(const PingPong_ping_result&);
  PingPong_ping_result& operator=(const PingPong_ping_result&);
  PingPong_ping_result() : success() {
  }

  virtual ~PingPong_ping_result() throw();
  std::string success;

  _PingPong_ping_result__isset __isset;

  void __set_success(const std::string& val);

  bool operator == (const PingPong_ping_result & rhs) const
  {
    if (!(success == rhs.success))
      return false;
    return true;
  }
  bool operator != (const PingPong_ping_result &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const PingPong_ping_result & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _PingPong_ping_presult__isset {
  _PingPong_ping_presult__isset() : success(false) {}
  bool success :1;
} _PingPong_ping_presult__isset;

class PingPong_ping_presult {
 public:


  virtual ~PingPong_ping_presult() throw();
  std::string* success;

  _PingPong_ping_presult__isset __isset;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);

};

typedef struct _PingPong_evaluate_args__isset {
  _PingPong_evaluate_args__isset() : msg(false) {}
  bool msg :1;
} _PingPong_evaluate_args__isset;

class PingPong_evaluate_args {
 public:

  PingPong_evaluate_args(const PingPong_evaluate_args&);
  PingPong_evaluate_args& operator=(const PingPong_evaluate_args&);
  PingPong_evaluate_args() : msg(0) {
  }

  virtual ~PingPong_evaluate_args() throw();
  double msg;

  _PingPong_evaluate_args__isset __isset;

  void __set_msg(const double val);

  bool operator == (const PingPong_evaluate_args & rhs) const
  {
    if (!(msg == rhs.msg))
      return false;
    return true;
  }
  bool operator != (const PingPong_evaluate_args &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const PingPong_evaluate_args & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class PingPong_evaluate_pargs {
 public:


  virtual ~PingPong_evaluate_pargs() throw();
  const double* msg;

  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _PingPong_evaluate_result__isset {
  _PingPong_evaluate_result__isset() : success(false) {}
  bool success :1;
} _PingPong_evaluate_result__isset;

class PingPong_evaluate_result {
 public:

  PingPong_evaluate_result(const PingPong_evaluate_result&);
  PingPong_evaluate_result& operator=(const PingPong_evaluate_result&);
  PingPong_evaluate_result() : success(0) {
  }

  virtual ~PingPong_evaluate_result() throw();
  double success;

  _PingPong_evaluate_result__isset __isset;

  void __set_success(const double val);

  bool operator == (const PingPong_evaluate_result & rhs) const
  {
    if (!(success == rhs.success))
      return false;
    return true;
  }
  bool operator != (const PingPong_evaluate_result &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const PingPong_evaluate_result & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _PingPong_evaluate_presult__isset {
  _PingPong_evaluate_presult__isset() : success(false) {}
  bool success :1;
} _PingPong_evaluate_presult__isset;

class PingPong_evaluate_presult {
 public:


  virtual ~PingPong_evaluate_presult() throw();
  double* success;

  _PingPong_evaluate_presult__isset __isset;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);

};

class PingPongClient : virtual public PingPongIf {
 public:
  PingPongClient(boost::shared_ptr< ::apache::thrift::protocol::TProtocol> prot) {
    setProtocol(prot);
  }
  PingPongClient(boost::shared_ptr< ::apache::thrift::protocol::TProtocol> iprot, boost::shared_ptr< ::apache::thrift::protocol::TProtocol> oprot) {
    setProtocol(iprot,oprot);
  }
 private:
  void setProtocol(boost::shared_ptr< ::apache::thrift::protocol::TProtocol> prot) {
  setProtocol(prot,prot);
  }
  void setProtocol(boost::shared_ptr< ::apache::thrift::protocol::TProtocol> iprot, boost::shared_ptr< ::apache::thrift::protocol::TProtocol> oprot) {
    piprot_=iprot;
    poprot_=oprot;
    iprot_ = iprot.get();
    oprot_ = oprot.get();
  }
 public:
  boost::shared_ptr< ::apache::thrift::protocol::TProtocol> getInputProtocol() {
    return piprot_;
  }
  boost::shared_ptr< ::apache::thrift::protocol::TProtocol> getOutputProtocol() {
    return poprot_;
  }
  void ping(std::string& _return, const std::string& msg);
  void send_ping(const std::string& msg);
  void recv_ping(std::string& _return);
  double evaluate(const double msg);
  void send_evaluate(const double msg);
  double recv_evaluate();
 protected:
  boost::shared_ptr< ::apache::thrift::protocol::TProtocol> piprot_;
  boost::shared_ptr< ::apache::thrift::protocol::TProtocol> poprot_;
  ::apache::thrift::protocol::TProtocol* iprot_;
  ::apache::thrift::protocol::TProtocol* oprot_;
};

class PingPongProcessor : public ::apache::thrift::TDispatchProcessor {
 protected:
  boost::shared_ptr<PingPongIf> iface_;
  virtual bool dispatchCall(::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, const std::string& fname, int32_t seqid, void* callContext);
 private:
  typedef  void (PingPongProcessor::*ProcessFunction)(int32_t, ::apache::thrift::protocol::TProtocol*, ::apache::thrift::protocol::TProtocol*, void*);
  typedef std::map<std::string, ProcessFunction> ProcessMap;
  ProcessMap processMap_;
  void process_ping(int32_t seqid, ::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, void* callContext);
  void process_evaluate(int32_t seqid, ::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, void* callContext);
 public:
  PingPongProcessor(boost::shared_ptr<PingPongIf> iface) :
    iface_(iface) {
    processMap_["ping"] = &PingPongProcessor::process_ping;
    processMap_["evaluate"] = &PingPongProcessor::process_evaluate;
  }

  virtual ~PingPongProcessor() {}
};

class PingPongProcessorFactory : public ::apache::thrift::TProcessorFactory {
 public:
  PingPongProcessorFactory(const ::boost::shared_ptr< PingPongIfFactory >& handlerFactory) :
      handlerFactory_(handlerFactory) {}

  ::boost::shared_ptr< ::apache::thrift::TProcessor > getProcessor(const ::apache::thrift::TConnectionInfo& connInfo);

 protected:
  ::boost::shared_ptr< PingPongIfFactory > handlerFactory_;
};

class PingPongMultiface : virtual public PingPongIf {
 public:
  PingPongMultiface(std::vector<boost::shared_ptr<PingPongIf> >& ifaces) : ifaces_(ifaces) {
  }
  virtual ~PingPongMultiface() {}
 protected:
  std::vector<boost::shared_ptr<PingPongIf> > ifaces_;
  PingPongMultiface() {}
  void add(boost::shared_ptr<PingPongIf> iface) {
    ifaces_.push_back(iface);
  }
 public:
  void ping(std::string& _return, const std::string& msg) {
    size_t sz = ifaces_.size();
    size_t i = 0;
    for (; i < (sz - 1); ++i) {
      ifaces_[i]->ping(_return, msg);
    }
    ifaces_[i]->ping(_return, msg);
    return;
  }

  double evaluate(const double msg) {
    size_t sz = ifaces_.size();
    size_t i = 0;
    for (; i < (sz - 1); ++i) {
      ifaces_[i]->evaluate(msg);
    }
    return ifaces_[i]->evaluate(msg);
  }

};

// The 'concurrent' client is a thread safe client that correctly handles
// out of order responses.  It is slower than the regular client, so should
// only be used when you need to share a connection among multiple threads
class PingPongConcurrentClient : virtual public PingPongIf {
 public:
  PingPongConcurrentClient(boost::shared_ptr< ::apache::thrift::protocol::TProtocol> prot) {
    setProtocol(prot);
  }
  PingPongConcurrentClient(boost::shared_ptr< ::apache::thrift::protocol::TProtocol> iprot, boost::shared_ptr< ::apache::thrift::protocol::TProtocol> oprot) {
    setProtocol(iprot,oprot);
  }
 private:
  void setProtocol(boost::shared_ptr< ::apache::thrift::protocol::TProtocol> prot) {
  setProtocol(prot,prot);
  }
  void setProtocol(boost::shared_ptr< ::apache::thrift::protocol::TProtocol> iprot, boost::shared_ptr< ::apache::thrift::protocol::TProtocol> oprot) {
    piprot_=iprot;
    poprot_=oprot;
    iprot_ = iprot.get();
    oprot_ = oprot.get();
  }
 public:
  boost::shared_ptr< ::apache::thrift::protocol::TProtocol> getInputProtocol() {
    return piprot_;
  }
  boost::shared_ptr< ::apache::thrift::protocol::TProtocol> getOutputProtocol() {
    return poprot_;
  }
  void ping(std::string& _return, const std::string& msg);
  int32_t send_ping(const std::string& msg);
  void recv_ping(std::string& _return, const int32_t seqid);
  double evaluate(const double msg);
  int32_t send_evaluate(const double msg);
  double recv_evaluate(const int32_t seqid);
 protected:
  boost::shared_ptr< ::apache::thrift::protocol::TProtocol> piprot_;
  boost::shared_ptr< ::apache::thrift::protocol::TProtocol> poprot_;
  ::apache::thrift::protocol::TProtocol* iprot_;
  ::apache::thrift::protocol::TProtocol* oprot_;
  ::apache::thrift::async::TConcurrentClientSyncInfo sync_;
};

#ifdef _WIN32
  #pragma warning( pop )
#endif



#endif
