/**
 * Autogenerated by Thrift Compiler (1.0.0-dev)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef robocup_CONSTANTS_H
#define robocup_CONSTANTS_H

#include "robocup_types.h"



class robocupConstants {
 public:
  robocupConstants();

};

extern const robocupConstants g_robocup_constants;



#endif
