/**
 * Autogenerated by Thrift Compiler (1.0.0-dev)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "robocup_constants.h"



const robocupConstants g_robocup_constants;

robocupConstants::robocupConstants() {
}



